# Generated by Django 4.0 on 2021-12-25 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('93e2658d-ff64-4b9b-ad1b-615b618eb8c5'), primary_key=True,
                                   serialize=False),
        ),
    ]
