# Generated by Django 4.0 on 2021-12-25 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_birthdaydate_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b2dae81e-2fc8-42ae-a934-ac27455ece8f'), primary_key=True,
                                   serialize=False),
        ),
    ]
