# Generated by Django 4.0 on 2021-12-25 04:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_user_birthdaydate_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 4, 38, 28, 867539)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('18ba9b88-9ccc-476b-b645-2450cdabf083'), primary_key=True,
                                   serialize=False),
        ),
    ]
