# Generated by Django 4.0 on 2022-01-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 29, 34, 390950)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 29, 34, 390967)),
        ),
    ]
