# Generated by Django 4.0 on 2022-01-16 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_birthdaydate_alter_user_uuid'),
        ('work', '0002_remove_project_users_alter_todo_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='users.User'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 53, 54, 337364)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 53, 54, 337383)),
        ),
    ]
