# Generated by Django 4.0 on 2021-12-25 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3ec326df-75bd-4940-8047-bac0484f3f1e'), primary_key=True,
                                   serialize=False),
        ),
    ]
