# Generated by Django 4.0 on 2021-12-25 04:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 4, 39, 57, 422544)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('21519123-5cd5-489c-981c-8643d5969858'), primary_key=True,
                                   serialize=False),
        ),
    ]
