# Generated by Django 4.0 on 2022-01-16 15:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthdaydate_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 58, 13, 295421)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('23d08e80-24f3-4426-b390-f43f1c6024a7'), primary_key=True, serialize=False),
        ),
    ]
