# Generated by Django 4.0 on 2022-01-16 16:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_birthdaydate_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 16, 1, 20, 854408)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79b79bc1-dbd9-455e-b3c1-b19ff9e45fed'), primary_key=True, serialize=False),
        ),
    ]
