# Generated by Django 4.0 on 2022-01-16 16:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_birthdaydate_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 16, 29, 34, 389289)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ad950966-31e0-4257-8677-16df0d1a4df2'), primary_key=True, serialize=False),
        ),
    ]
