# Generated by Django 4.0 on 2022-01-16 16:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_birthdaydate_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdaydate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 16, 53, 54, 334857)),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1bb1368a-2782-4fd6-8851-1b445e757698'), primary_key=True, serialize=False),
        ),
    ]
